language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - psql createuser --superuser ndraper2
  - psql -c 'create database test_learning_journal;' -U ndraper2
  - psql -U ndraper2 -c "create extension postgis"
script: lettuce